apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.consumerhost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-nginx-consumer
            port: 
              number: {{ .Values.consumer.httpport }}