consumerhost: "ingress-nginx-controller.ingress-nginx"

producer:
  consumerurl: "http://ingress-nginx-controller.ingress-nginx:80/cpu"
  timeout: 30
  workercount: 10
  rates: "3000,6000,9000,12000,15000,12000,9000,6000,3000,0"
  cnts: "1,1,1,1,1,1,1,1,1,1"

consumer:
  httpport: 30080
  shutdowntimeout: 30
  cpu:
    loopcnt: 10000